keys:
  - &mtpham_grunfeld age196hvhgns95l08maw7eg9stzuuewjcm7f9u86yr2fuq6565rnmslswnenc2
  - &hci-admin age18h3fzsk6uz4gml7j3hks9wtuu8wvda6959m3ayt9vxl68dpwkfwsur5n5g
  - &hci01 age1d3y2unlh3z7dep4c9u2m89qh2f9qvjapk0ll396n0wzm6gm3g49sh048hc
  - &hci02 age1geehpwddcnva5yxlx60unt3qtvz7gw06m30z43ylk6ypc0ml3q0q8xplzf
  - &hci03 age1mlqyp8uwrut56d32722nxeh0jv8rq4kcny9upcqs22dtx24krajqh55rem
creation_rules:
  - path_regex: '^hci\.enc\.ya?ml$'
    key_groups:
      - age:
          - *mtpham_grunfeld
          - *hci-admin
          - *hci01
          - *hci02
          - *hci03
  - path_regex: '.*\.ya?ml$'
    key_groups:
      - age:
          - *mtpham_grunfeld
